# This file is centrally managed as a template file in https://github.com/canonical/solutions-engineering-automation
# To update the file:
# - Edit it in the canonical/solutions-engineering-automation repository.
# - Open a PR with the changes.
# - When the PR merges, the soleng-terraform bot will open a PR to the target repositories with the changes.

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "snap-tempest"
version = "2026.1"
description = "OpenStack Tempest snap wrapper"
requires-python = ">=3.14"
dependencies = [
    "tempest @ git+https://opendev.org/openstack/tempest.git@34.1.0",
    "confluent-kafka==1.8.2",
    "barbican-tempest-plugin @ git+https://opendev.org/openstack/barbican-tempest-plugin.git@2.0.0",
    "blazar-tempest-plugin @ git+https://opendev.org/openstack/blazar-tempest-plugin.git@0.10.1",
    "cinder-tempest-plugin @ git+https://opendev.org/openstack/cinder-tempest-plugin.git@1.8.1",
    "cloudkitty-tempest-plugin @ git+https://opendev.org/openstack/cloudkitty-tempest-plugin.git@2.7.1",
    "cyborg-tempest-plugin @ git+https://opendev.org/openstack/cyborg-tempest-plugin.git@2.1.0",
    "designate-tempest-plugin @ git+https://opendev.org/openstack/designate-tempest-plugin.git@0.17.0",
    "ec2api-tempest-plugin @ git+https://opendev.org/openstack/ec2api-tempest-plugin.git@1.6.1",
    "freezer-tempest-plugin @ git+https://opendev.org/openstack/freezer-tempest-plugin.git@3.0.1",
    "glance-tempest-plugin @ git+https://opendev.org/openstack/glance-tempest-plugin.git@0.6.0",
    "heat-tempest-plugin @ git+https://opendev.org/openstack/heat-tempest-plugin.git@1.7.1",
    "ironic-tempest-plugin @ git+https://opendev.org/openstack/ironic-tempest-plugin.git@2.6.1",
    "keystone-tempest-plugin @ git+https://opendev.org/openstack/keystone-tempest-plugin.git@0.12.0",
    "kuryr-tempest-plugin @ git+https://opendev.org/openstack/kuryr-tempest-plugin.git@0.14.1",
    "magnum-tempest-plugin @ git+https://opendev.org/openstack/magnum-tempest-plugin.git@2.0.0",
    "manila-tempest-plugin @ git+https://opendev.org/openstack/manila-tempest-plugin.git@1.13.0",
    "mistral-tempest-tests @ git+https://opendev.org/openstack/mistral-tempest-plugin.git@2.1.1",
    "monasca-tempest-plugin @ git+https://opendev.org/openstack/monasca-tempest-plugin.git@2.6.0",
    "murano-tempest-plugin @ git+https://opendev.org/openstack/murano-tempest-plugin.git@2.6.0",
    "neutron-tempest-plugin @ git+https://opendev.org/openstack/neutron-tempest-plugin.git@2.2.0",
    "octavia-tempest-plugin @ git+https://opendev.org/openstack/octavia-tempest-plugin.git@2.3.0",
    "oswin-tempest-plugin @ git+https://opendev.org/openstack/oswin-tempest-plugin.git@2.1.0",
    "senlin-tempest-plugin @ git+https://opendev.org/openstack/senlin-tempest-plugin.git@1.7.1",
    "solum-tempest-plugin @ git+https://opendev.org/openstack/solum-tempest-plugin.git@2.6.0",
    "telemetry-tempest-plugin @ git+https://opendev.org/openstack/telemetry-tempest-plugin.git@1.9.0",
    "trove-tempest-plugin @ git+https://opendev.org/openstack/trove-tempest-plugin.git@2.0.1",
    "venus-tempest-plugin @ git+https://opendev.org/openstack/venus-tempest-plugin.git@3.0.0",
    "vitrage-tempest-plugin @ git+https://opendev.org/openstack/vitrage-tempest-plugin.git@6.1.1",
    "watcher-tempest-plugin @ git+https://opendev.org/openstack/watcher-tempest-plugin.git@2.6.0",
    "zaqar-tempest-plugin @ git+https://opendev.org/openstack/zaqar-tempest-plugin.git@1.6.0",
    "zun-tempest-plugin @ git+https://opendev.org/openstack/zun-tempest-plugin.git@4.7.1",
    "python-tempestconf @ git+https://opendev.org/openinfra/python-tempestconf.git@3.4.0",
]

[tool.setuptools_scm]

[tool.flake8]
max-line-length = 99
max-doc-length = 99
max-complexity = 10
exclude = [
    ".git",
    "__pycache__",
    ".tox",
    ".build",
    "build",
    "dist",
    ".eggs",
    "*.egg_info",
    "venv",
    ".venv",
    "report",
    "docs",
    "lib",
    "mod",
    "hooks/charmhelpers",
    "tests/charmhelpers",
]
select = ["E", "W", "F", "C", "N", "R", "D", "H"]
# Ignore W503, E501 because using black creates errors with this
# Ignore D107 Missing docstring in __init__
# Ignore D415 Docstring first line punctuation (doesn't make sense for properties)
# Ignore N818 Exceptions end with "Error" (not all exceptions are errors)
# D100, D101, D102, D103: Ignore missing docstrings in tests
ignore = ["C901", "W503", "E501", "D107", "D415", "N818", "D100", "D101", "D102", "D103", "W504"]
per-file-ignores = ["tests/*:D100,D101,D102,D103,D104"]
# Check for properly formatted copyright header in each file
copyright-check = "True"
copyright-author = "Canonical Ltd."
copyright-regexp = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+%(author)s"

[tool.black]
line-length = 99
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | build
    | lib
    | report
    | docs
    | mod
    | hooks/charmhelpers
    | tests/charmhelpers
)/
'''

[tool.isort]
profile = "black"
line_length = 99
skip_glob = [".eggs", ".git", ".tox", ".venv", ".build", "build", "lib", "report", "mod/*", "hooks/charmhelpers", "tests/charmhelpers"]

[tool.pylint]
max-line-length = 99
disable = ["E1102"]
ignore = ['.eggs', '.git', '.tox', '.venv', '.build', 'lib', 'report', 'tests', 'docs', "mod", "hooks/charmhelpers", "tests/charmhelpers"]

[tool.mypy]
warn_unused_ignores = true
warn_unused_configs = true
warn_unreachable = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_namespace_packages = true
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'lib', 'report', 'tests', 'docs', "mod", "hooks/charmhelpers", "tests/charmhelpers"]

[tool.codespell]
skip = ".eggs,.tox,.git,.venv,venv,build,.build,lib,report,docs,poetry.lock,htmlcov,mod,hooks/charmhelpers,tests/charmhelpers"
quiet-level = 3
check-filenames = true
ignore-words-list = "assertIn"

## Ignore unsupported imports
[[tool.mypy.overrides]]
module = ["charmhelpers.*", "setuptools"]
ignore_missing_imports = true

[tool.coverage.run]
relative_files = true
source = ["."]
omit = ["tests/**", "docs/**", "lib/**", "snap/**", "build/**", "setup.py", "mod/**", "hooks/charmhelpers/**", "tests/charmhelpers/**"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.html]
directory = "tests/report/html"

[tool.coverage.xml]
output = "tests/report/coverage.xml"
