# This is a template `pyproject.toml` file for snaps
# This file is managed by bootstack-charms-spec and should not be modified
# within individual snap repos. https://launchpad.net/bootstack-charms-spec

[tool.flake8]
ignore = ["C901", "D100", "D101", "D102", "D103", "W503", "W504"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'build', 'report']
max-line-length = 99
max-complexity = 10

[tool.black]
line-length = 99
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | build
    | report
)/
'''

[tool.isort]
profile = "black"
skip_glob = [
  ".eggs",
  ".git",
  ".tox",
  ".venv",
  ".build",
  "build",
  "report"
]

[tool.pylint]
max-line-length = 99
extension-pkg-allow-list = "pygit2"
ignore-paths = [
  ".eggs",
  ".git",
  ".tox",
  ".venv",
  ".build",
  "report",
  "tests",
]
