name: tempest
adopt-info: tempest
summary: OpenStack Integration Test Suite
description: |
 Tempest is a set of integration tests to be run against a live
 OpenStack cluster. Tempest has batteries of tests for OpenStack
 API validation, Scenarios, and other specific tests useful in
 validating an OpenStack deployment.
confinement: strict
grade: stable
base: core22
assumes:
- command-chain

apps:
  tempest:
    command: bin/tempest
    command-chain: [bin/tempest-wrapper]
    completer: usr/share/bash-completion/completions/tempest
    plugs:
      - network-observe
      - network
      - home
    environment:
      TESTS: $SNAP_DATA/tempest_test_lists

  discover:
    command: bin/discover-tempest-config
    environment:
      # NOTE (rgildein): python-tempestconf uses urllib3 and it needs SSL_CERT_FILE to be
      # set if ca certificates are not in the standard locations.
      # https://www.openssl.org/docs/manmaster/man3/SSL_CTX_load_verify_locations.html
      SSL_CERT_FILE: $OS_CACERT
    plugs:
      - home
      - network

parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    organize:
      tempest-wrapper: bin/tempest-wrapper
  tempest:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    python-packages:
      # NOTE (mertkirpici): confluent-kafka versions are compatible with the same
      # librdkafka versions. jammy repositories have librdkafka==1.8
      # https://github.com/confluentinc/confluent-kafka-python/releases
      - confluent-kafka==1.8.2
    build-packages:
      - libssl-dev
      - libffi-dev
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev
      - librdkafka-dev
      - rustc
      - cargo
      - pkg-config
    override-prime: |
      craftctl default
      craftctl set version="$(tempest --version | awk '{print $2}')"
      mkdir -p usr/share/bash-completion/completions
      bin/tempest complete > usr/share/bash-completion/completions/tempest
      echo "complete -F _tempest tempest.tempest" >> usr/share/bash-completion/completions/tempest
