name: tempest
adopt-info: tempest
summary: OpenStack Integration Test Suite
description: |
 Tempest is a set of integration tests to be run against a live
 OpenStack cluster. Tempest has batteries of tests for OpenStack
 API validation, Scenarios, and other specific tests useful in
 validating an OpenStack deployment.
confinement: strict
grade: stable
base: core22

apps:
  tempest:
    command: tempest-wrapper
    completer: usr/share/bash-completion/completions/tempest
    plugs:
      - network-observe
      - network
      - home

parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    override-build: |
      cp tempest-wrapper $CRAFT_PART_INSTALL/
      cp -r tempest_test_lists $CRAFT_PART_INSTALL/
  tempest:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    override-prime: |
      craftctl default
      craftctl set version="$(tempest --version | awk '{print $2}')"
      mkdir -p usr/share/bash-completion/completions
      bin/tempest complete > usr/share/bash-completion/completions/tempest
      echo "complete -F _tempest tempest.tempest" >> usr/share/bash-completion/completions/tempest
