name: tempest
adopt-info: tempest
summary: OpenStack Integration Test Suite
description: |
  Tempest is a set of integration tests to be run against a live
  OpenStack cluster. Tempest has batteries of tests for OpenStack
  API validation, Scenarios, and other specific tests useful in
  validating an OpenStack deployment.
license: Apache-2.0
confinement: strict
grade: stable
base: core20
assumes:
- command-chain
apps:
  tempest:
    command: bin/tempest
    command-chain:
    - bin/tempest-wrapper
    completer: usr/share/bash-completion/completions/tempest
    plugs:
    - network-observe
    - network
    - home
    environment:
      TESTS: $SNAP_DATA/tempest_test_lists
  discover:
    command: bin/discover-tempest-config
    environment:
      SSL_CERT_FILE: $OS_CACERT
    plugs:
    - home
    - network
parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    organize:
      tempest-wrapper: bin/tempest-wrapper
  tempest:
    plugin: python
    source: https://opendev.org/openstack/tempest.git
    source-type: git
    source-tag: ussuri-last
    python-packages:
    - confluent-kafka==1.2.0
    - git+https://opendev.org/openstack/barbican-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/blazar-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/cinder-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/cloudkitty-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/congress-tempest-plugin.git@1.0.0
    - git+https://opendev.org/openstack/cyborg-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/designate-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/ec2api-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/freezer-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/heat-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/ironic-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/keystone-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/kuryr-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/magnum-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/manila-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/mistral-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/monasca-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/murano-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/neutron-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/octavia-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/oswin-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/sahara-tests.git@ussuri-last
    - git+https://opendev.org/openstack/senlin-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/solum-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/telemetry-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/tempest-horizon.git@1.1.0
    - git+https://opendev.org/openstack/trove-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/vitrage-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/watcher-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/zaqar-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openstack/zun-tempest-plugin.git@ussuri-last
    - git+https://opendev.org/openinfra/python-tempestconf.git@3.4.2
    build-packages:
    - libssl-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - librdkafka-dev
    - rustc
    - cargo
    - pkg-config
    - git
    override-stage: |
      snapcraftctl stage
      snapcraftctl set-version "$(tempest --version | awk '{print $2}')"
    override-prime: |
      snapcraftctl prime
      mkdir -p usr/share/bash-completion/completions
      bin/tempest complete > usr/share/bash-completion/completions/tempest
      echo "complete -F _tempest tempest.tempest" >> usr/share/bash-completion/completions/tempest
