name: tempest
adopt-info: tempest
summary: OpenStack Integration Test Suite
description: |
  Tempest is a set of integration tests to be run against a live
  OpenStack cluster. Tempest has batteries of tests for OpenStack
  API validation, Scenarios, and other specific tests useful in
  validating an OpenStack deployment.
license: Apache-2.0
confinement: strict
grade: stable
base: core22
assumes:
- command-chain
apps:
  tempest:
    command: bin/tempest
    command-chain:
    - bin/tempest-wrapper
    completer: usr/share/bash-completion/completions/tempest
    plugs:
    - network-observe
    - network
    - home
    environment:
      TESTS: $SNAP_DATA/tempest_test_lists
  discover:
    command: bin/discover-tempest-config
    environment:
      SSL_CERT_FILE: $OS_CACERT
    plugs:
    - home
    - network
parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    organize:
      tempest-wrapper: bin/tempest-wrapper
  tempest:
    plugin: python
    source: https://opendev.org/openstack/tempest.git
    source-type: git
    source-tag: 39.0.0
    python-packages:
      # confluent-kafka is needed by the monasca plugin
      # see https://github.com/canonical/snap-tempest/pull/10#issuecomment-1682115758
      # confluent-kafka versions are compatible with the same librdkafka versions,
      # so the version must match that of the base ubuntu release, which is currently jammy.
      # jammy repositories have librdkafka==1.8
    - git+https://opendev.org/openstack/barbican-tempest-plugin.git@4.0.0
    - git+https://opendev.org/openstack/cinder-tempest-plugin.git@1.14.0
    - git+https://opendev.org/openstack/designate-tempest-plugin.git@0.22.0
    - git+https://opendev.org/openstack/glance-tempest-plugin.git@0.9.0
    - git+https://opendev.org/openstack/heat-tempest-plugin.git@2.2.0
    - git+https://opendev.org/openstack/ironic-tempest-plugin.git@2.10.0
    - git+https://opendev.org/openstack/keystone-tempest-plugin.git@0.16.0
    - git+https://opendev.org/openstack/magnum-tempest-plugin.git@2.4.0
    - git+https://opendev.org/openstack/manila-tempest-plugin.git@2.4.0
    - git+https://opendev.org/openstack/neutron-tempest-plugin.git@2.8.0
    - git+https://opendev.org/openstack/octavia-tempest-plugin.git@2.7.0
    - git+https://opendev.org/openstack/telemetry-tempest-plugin.git@2.2.0
    - git+https://opendev.org/openinfra/python-tempestconf.git@3.5.0
    build-packages:
    - libssl-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - librdkafka-dev
    - rustc
    - cargo
    - pkg-config
    - git
    override-prime: |
      craftctl default
      craftctl set version="$(tempest --version | awk '{print $2}')"
      mkdir -p usr/share/bash-completion/completions
      bin/tempest complete > usr/share/bash-completion/completions/tempest
      echo "complete -F _tempest tempest.tempest" >> usr/share/bash-completion/completions/tempest
