name: tempest
version: 14.0.0
summary: OpenStack Integration Test Suite
description: |
 Tempest is a set of integration tests to be run against a live
 OpenStack cluster. Tempest has batteries of tests for OpenStack
 API validation, Scenarios, and other specific tests useful in
 validating an OpenStack deployment.
confinement: classic
grade: devel

apps:
  tempest:
    command: tempest
    plugs:
      - network
      - network-bind
      - home
  tempest-account-generator:
    command: tempest-account-generator
    plugs:
      - network
      - network-bind
      - home
    aliases:
      - tempest-account-generator

parts:
  tempest:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/tempest/tempest-14.0.0.tar.gz
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - gcc
